# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=2, upload_to=b''),
            preserve_default=False,
        ),
    ]
