# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_auto_20160725_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
