# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_auto_20160725_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
