# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='image',
            field=models.CharField(default=datetime.datetime(2016, 11, 12, 1, 47, 29, 775678, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
