# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_thought_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='image',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
