# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_thought_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='likes',
        ),
    ]
