# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-12 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_thought_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thought',
            new_name='bella',
        ),
    ]
